# Sync HIGH-tier slugs from pattern-catalog.md into HIGH-TIER-SLUGS.md.
#
# pattern-catalog.md is the CANONICAL source; HIGH-TIER-SLUGS.md is derived.
# Base instruction files (AGENTS.md, csharp.instructions.md, etc.) reference
# HIGH-TIER-SLUGS.md by pointer. After context compaction, the agent's
# auto-loaded base files retain the load-bearing rules (in actionable form);
# HIGH-TIER-SLUGS.md provides the per-slug 1-line trigger summary.
#
# Modes:
#   default:        regenerate HIGH-TIER-SLUGS.md from pattern-catalog.md
#   -Verify:        compare in-memory generation to on-disk; exit non-zero if drift
#   -StagedMode:    read both files via `git show :<path>` (staged index content)
#                   instead of working tree; for pre-commit hook use.
#
# Cross-platform invariants (designed for byte-identical output to scripts/sync-critical-rules.sh):
#   - Content hash uses `git hash-object` (canonical normalized blob SHA-1; immune
#     to CRLF/LF drift across platforms). NOT git-log SHA (chicken-and-egg) and NOT
#     raw file-byte SHA-256 (CRLF/LF platform sensitivity).
#   - All emitted lines use explicit "`n" literals (NOT AppendLine, which emits
#     `r`n on Windows pwsh). Output is LF-only on every platform.
#   - Generated output written with utf8NoBOM encoding, no trailing newline.

[CmdletBinding()]
param(
    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\.github\pr-quality-gate\pattern-catalog.md'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\.github\pr-quality-gate\HIGH-TIER-SLUGS.md'),
    [switch] $Verify,
    [switch] $StagedMode
)

$ErrorActionPreference = 'Stop'

# Resolve the repo root so `git show :<path>` and `git hash-object <path>` use repo-relative paths.
$repoRoot = & git -C (Split-Path $CatalogPath -Parent) rev-parse --show-toplevel 2>$null
if (-not $repoRoot) { throw "Not in a git repo (cannot resolve repo root from $CatalogPath)" }
$repoRoot = $repoRoot.Trim()

# Compute repo-relative paths for git commands.
$catalogAbs = (Resolve-Path -LiteralPath $CatalogPath -ErrorAction SilentlyContinue)
if (-not $catalogAbs -and -not $StagedMode) { throw "Catalog not found: $CatalogPath" }
$catalogRelPath = if ($catalogAbs) {
    [System.IO.Path]::GetRelativePath($repoRoot, $catalogAbs.Path) -replace '\\', '/'
} else {
    '.github/pr-quality-gate/pattern-catalog.md'
}
$outputRelPath = '.github/pr-quality-gate/HIGH-TIER-SLUGS.md'

# Read pattern-catalog content. -StagedMode reads from git index; default reads working tree.
if ($StagedMode) {
    $catalogContent = & git -C $repoRoot show ":$catalogRelPath" 2>$null
    if (-not $catalogContent) { throw "Cannot read staged content of $catalogRelPath. Is it staged?" }
    $lines = $catalogContent -split "`r?`n"
    # Hash via git rev-parse (returns the staged blob SHA-1 directly; cheapest path).
    $catalogHash = (& git -C $repoRoot rev-parse ":$catalogRelPath" 2>$null).Trim()
} else {
    if (-not (Test-Path -LiteralPath $CatalogPath)) { throw "Catalog not found: $CatalogPath" }
    $lines = Get-Content -LiteralPath $CatalogPath -Encoding UTF8
    # `git hash-object` runs the clean filter (respects .gitattributes text=auto) so the
    # computed hash matches what git would store on `git add`. Cross-platform stable.
    $catalogHash = (& git -C $repoRoot hash-object $catalogRelPath 2>$null).Trim()
}
if (-not $catalogHash) { $catalogHash = 'unknown' }

$highTierSlugs = @()
foreach ($line in $lines) {
    if ($line -notmatch '^\|') { continue }
    if ($line -match '^\|\s*slug\s*\|' -or $line -match '^\|\s*-+\s*\|') { continue }
    if ($line -match '^\|\s*tier\s*\|') { continue }
    $cellsRaw = ($line -split '(?<!\\)\|')
    if ($cellsRaw.Count -lt 2) { continue }
    $cells = $cellsRaw[1..($cellsRaw.Count - 2)] | ForEach-Object { $_.Trim() }
    if ($cells.Count -lt 6) { continue }
    if ($cells[5] -ne 'HIGH') { continue }
    $slug = $cells[0]
    $scope = $cells[1]
    if ($scope -ne 'review-pass-only') { continue }
    $prompt = $cells[3]
    # Unescape `\|` placeholder back to literal `|` — matches the bash twin's awk \001 round-trip
    # so HIGH-TIER-SLUGS.md is byte-identical regardless of which generator wrote it.
    $prompt = $prompt -replace '\\\|', '|'
    $trigger = ($prompt -split '\. ', 2)[0]
    if ($trigger.Length -gt 200) { $trigger = $trigger.Substring(0, 197) + '...' }
    $highTierSlugs += [pscustomobject]@{
        Slug = $slug
        Scope = $scope
        Trigger = $trigger
    }
}

# Build output with explicit "`n" literals — LF-only on every platform, byte-identical to bash twin.
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("# HIGH-TIER catalog slugs`n")
[void]$sb.Append("`n")
[void]$sb.Append("GENERATED FILE - do not hand-edit. Regenerated by ``scripts/sync-critical-rules.ps1`` or its bash twin ``scripts/sync-critical-rules.sh`` from ``pattern-catalog.md``.`n")
[void]$sb.Append("`n")
[void]$sb.Append("Catalog content hash: ``${catalogHash}```n")
[void]$sb.Append("`n")
[void]$sb.Append("Every HIGH-tier ``review-pass-only`` slug below MUST appear in ``core_rules_acknowledged`` on every commit with per-site ``file:line:disposition`` citations (see ``panel-policy.md`` §Per-rule acknowledgement for full schema).`n")
[void]$sb.Append("`n")
[void]$sb.Append("## Slugs requiring acknowledgement`n")
[void]$sb.Append("`n")
foreach ($s in $highTierSlugs) {
    [void]$sb.Append("### ``$($s.Slug)```n")
    [void]$sb.Append("`n")
    [void]$sb.Append($s.Trigger + ".`n")
    [void]$sb.Append("`n")
    [void]$sb.Append("Canonical rule definition: see ``pattern-catalog.md`` row ``$($s.Slug)``.`n")
    [void]$sb.Append("`n")
}
[void]$sb.Append("## Acknowledgement template (per-slug)`n")
[void]$sb.Append("`n")
[void]$sb.Append("``````yaml`n")
[void]$sb.Append("core_rules_acknowledged:`n")
[void]$sb.Append("  - slug: <slug>`n")
[void]$sb.Append("    status: <applied | not-applicable>`n")
[void]$sb.Append("    evidence:`n")
[void]$sb.Append("      per_site_citations:`n")
[void]$sb.Append("        - file: <path>`n")
[void]$sb.Append("          line: <int or range>`n")
[void]$sb.Append("          disposition: <rename | extract | remove | restore | keep-because>`n")
[void]$sb.Append("          keep_reason: <≤12 words; MUST add information beyond comment text>`n")
[void]$sb.Append("      diff_metric_check: <rg-violation count vs per_site_citations count>`n")
[void]$sb.Append("    rationale: <≤30 words; required for not-applicable>`n")
[void]$sb.Append("``````")

$generated = $sb.ToString()

if ($Verify) {
    if ($StagedMode) {
        $existing = & git -C $repoRoot show ":$outputRelPath" 2>$null
        if (-not $existing) {
            Write-Error "HIGH-TIER-SLUGS.md missing from staged index. Run sync-critical-rules.ps1 (no flags) and stage the result."
            exit 1
        }
        # git show returns text with platform line endings; normalize for compare.
        $existing = $existing -join "`n"
    } else {
        if (-not (Test-Path -LiteralPath $OutputPath)) {
            Write-Error "HIGH-TIER-SLUGS.md missing at $OutputPath; run sync-critical-rules.ps1 (without -Verify) to generate."
            exit 1
        }
        $existing = (Get-Content -LiteralPath $OutputPath -Raw -Encoding UTF8)
    }
    # Both sides normalized to LF for comparison.
    $existingNorm = $existing -replace "`r`n", "`n"
    $generatedNorm = $generated -replace "`r`n", "`n"
    if ($existingNorm -ne $generatedNorm) {
        $mode = if ($StagedMode) { 'staged index' } else { 'working tree' }
        Write-Error "HIGH-TIER-SLUGS.md ($mode) is OUT OF SYNC with pattern-catalog.md. Run scripts/sync-critical-rules.ps1 to regenerate, then stage the result."
        exit 1
    }
    Write-Host "HIGH-TIER-SLUGS.md is in sync."
    exit 0
}

# Atomic write: temp file then rename. utf8NoBOM, no trailing newline.
$tempPath = "$OutputPath.tmp"
[System.IO.File]::WriteAllText($tempPath, $generated, (New-Object System.Text.UTF8Encoding($false)))
Move-Item -LiteralPath $tempPath -Destination $OutputPath -Force

Write-Host "Generated $OutputPath with $($highTierSlugs.Count) HIGH-tier review-pass-only slugs (content hash: $catalogHash)."
