# Sync HIGH-tier slugs from pattern-catalog.md into HIGH-TIER-SLUGS.md.
#
# pattern-catalog.md is the CANONICAL source; HIGH-TIER-SLUGS.md is derived.
# Base instruction files (AGENTS.md, csharp.instructions.md, etc.) reference
# HIGH-TIER-SLUGS.md by pointer. After context compaction, the agent's
# auto-loaded base files retain the load-bearing rules (in actionable form);
# HIGH-TIER-SLUGS.md provides the per-slug 1-line trigger summary.
#
# Modes:
#   default: regenerate HIGH-TIER-SLUGS.md from pattern-catalog.md
#   -Verify: compare in-memory generation to on-disk; exit non-zero if drift

[CmdletBinding()]
param(
    [string] $CatalogPath = (Join-Path $PSScriptRoot '..\.github\pr-quality-gate\pattern-catalog.md'),
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\.github\pr-quality-gate\HIGH-TIER-SLUGS.md'),
    [switch] $Verify
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $CatalogPath)) { throw "Catalog not found: $CatalogPath" }

$lines = Get-Content -LiteralPath $CatalogPath -Encoding UTF8

$catalogRev = & git -C (Split-Path $CatalogPath -Parent) log -1 --format=%H -- (Split-Path $CatalogPath -Leaf) 2>$null
if (-not $catalogRev) { $catalogRev = 'unknown' } else { $catalogRev = $catalogRev.Trim() }

$highTierSlugs = @()
foreach ($line in $lines) {
    if ($line -notmatch '^\|') { continue }
    if ($line -match '^\|\s*slug\s*\|' -or $line -match '^\|\s*-+\s*\|') { continue }
    if ($line -match '^\|\s*tier\s*\|') { continue }
    $cellsRaw = ($line -split '(?<!\\)\|')
    if ($cellsRaw.Count -lt 2) { continue }
    $cells = $cellsRaw[1..($cellsRaw.Count - 2)] | ForEach-Object { $_.Trim() }
    if ($cells.Count -lt 6) { continue }
    if ($cells[5] -ne 'HIGH') { continue }
    $slug = $cells[0]
    $scope = $cells[1]
    if ($scope -ne 'review-pass-only') { continue }
    $prompt = $cells[3]
    # Extract first sentence (up to first period or 200 chars) as trigger summary.
    $trigger = ($prompt -split '\. ', 2)[0]
    if ($trigger.Length -gt 200) { $trigger = $trigger.Substring(0, 197) + '...' }
    $highTierSlugs += [pscustomobject]@{
        Slug = $slug
        Scope = $scope
        Trigger = $trigger
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# HIGH-TIER catalog slugs')
[void]$sb.AppendLine()
[void]$sb.AppendLine('GENERATED FILE — do not hand-edit. Regenerated by `scripts/sync-critical-rules.ps1` from `pattern-catalog.md`.')
[void]$sb.AppendLine()
[void]$sb.AppendLine("Catalog source: ``pattern-catalog.md`` @ ``${catalogRev}``")
[void]$sb.AppendLine()
[void]$sb.AppendLine('Every HIGH-tier `review-pass-only` slug below MUST appear in `core_rules_acknowledged` on every commit with per-site `file:line:disposition` citations (see `panel-policy.md` §Per-rule acknowledgement for full schema).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Slugs requiring acknowledgement')
[void]$sb.AppendLine()
foreach ($s in $highTierSlugs) {
    [void]$sb.AppendLine("### ``$($s.Slug)``")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($s.Trigger + '.')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("Canonical rule definition: see ``pattern-catalog.md`` row ``$($s.Slug)``.")
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine('## Acknowledgement template (per-slug)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('```yaml')
[void]$sb.AppendLine('core_rules_acknowledged:')
[void]$sb.AppendLine('  - slug: <slug>')
[void]$sb.AppendLine('    status: <applied | not-applicable>')
[void]$sb.AppendLine('    evidence:')
[void]$sb.AppendLine('      per_site_citations:')
[void]$sb.AppendLine('        - file: <path>')
[void]$sb.AppendLine('          line: <int or range>')
[void]$sb.AppendLine('          disposition: <rename | extract | remove | restore | keep-because>')
[void]$sb.AppendLine('          keep_reason: <≤12 words; MUST add information beyond comment text>')
[void]$sb.AppendLine('      diff_metric_check: <rg-violation count vs per_site_citations count>')
[void]$sb.AppendLine('    rationale: <≤30 words; required for not-applicable>')
[void]$sb.AppendLine('```')

$generated = $sb.ToString()

if ($Verify) {
    if (-not (Test-Path -LiteralPath $OutputPath)) { Write-Error "HIGH-TIER-SLUGS.md missing at $OutputPath; run sync-critical-rules.ps1 (without -Verify) to generate."; exit 1 }
    $existing = (Get-Content -LiteralPath $OutputPath -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $generatedNormalized = $generated -replace "`r`n", "`n"
    if ($existing -ne $generatedNormalized) {
        Write-Error "HIGH-TIER-SLUGS.md is OUT OF SYNC with pattern-catalog.md. Run sync-critical-rules.ps1 (no flags) to regenerate."
        exit 1
    }
    Write-Host "HIGH-TIER-SLUGS.md is in sync."
    exit 0
}

# Atomic write: temp file then rename
$tempPath = "$OutputPath.tmp"
$generated | Out-File -LiteralPath $tempPath -Encoding utf8NoBOM -NoNewline
Move-Item -LiteralPath $tempPath -Destination $OutputPath -Force

Write-Host "Generated $OutputPath with $($highTierSlugs.Count) HIGH-tier review-pass-only slugs."
